weather_code_map = {
    0: {"description": "Ensolarado", "image": "http://openweathermap.org/img/wn/01d@2x.png"},
    1: {"description": "Principalmente ensolarado", "image": "http://openweathermap.org/img/wn/01d@2x.png"},
    2: {"description": "Parcialmente nublado", "image": "http://openweathermap.org/img/wn/02d@2x.png"},
    3: {"description": "Nublado", "image": "http://openweathermap.org/img/wn/03d@2x.png"},
    45: {"description": "Nebuloso", "image": "http://openweathermap.org/img/wn/50d@2x.png"},
    48: {"description": "Neblina com geada", "image": "http://openweathermap.org/img/wn/50d@2x.png"},
    51: {"description": "Garoa leve", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    53: {"description": "Garoa", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    55: {"description": "Garoa intensa", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    56: {"description": "Garoa leve congelante", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    57: {"description": "Garoa congelante", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    61: {"description": "Chuva leve", "image": "http://openweathermap.org/img/wn/10d@2x.png"},
    63: {"description": "Chuva", "image": "http://openweathermap.org/img/wn/10d@2x.png"},
    65: {"description": "Chuva intensa", "image": "http://openweathermap.org/img/wn/10d@2x.png"},
    66: {"description": "Chuva leve congelante", "image": "http://openweathermap.org/img/wn/10d@2x.png"},
    67: {"description": "Chuva congelante", "image": "http://openweathermap.org/img/wn/10d@2x.png"},
    71: {"description": "Neve leve", "image": "http://openweathermap.org/img/wn/13d@2x.png"},
    73: {"description": "Neve", "image": "http://openweathermap.org/img/wn/13d@2x.png"},
    75: {"description": "Neve intensa", "image": "http://openweathermap.org/img/wn/13d@2x.png"},
    77: {"description": "Grãos de neve", "image": "http://openweathermap.org/img/wn/13d@2x.png"},
    80: {"description": "Aguaceiros leves", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    81: {"description": "Aguaceiros", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    82: {"description": "Aguaceiros intensos", "image": "http://openweathermap.org/img/wn/09d@2x.png"},
    85: {"description": "Aguaceiros de neve leve", "image": "http://openweathermap.org/img/wn/13d@2x.png"},
    86: {"description": "Aguaceiros de neve", "image": "http://openweathermap.org/img/wn/13d@2x.png"},
    95: {"description": "Tempestade", "image": "http://openweathermap.org/img/wn/11d@2x.png"},
    96: {"description": "Tempestade com granizo leve", "image": "http://openweathermap.org/img/wn/11d@2x.png"},
    99: {"description": "Tempestade com granizo intenso", "image": "http://openweathermap.org/img/wn/11d@2x.png"}
}
